pipeline {
    agent any

    environment {
        DOCKER_IMAGE = 'abkaur95/api-gateway'
        DOCKER_CREDENTIALS_ID = 'dockerhub'
    }

    stages {
        stage('Build') {
            steps {
                dir('api-gateway') {
                    sh 'mvn clean install -DskipTests'
                }
            }
        }

        stage('Docker Build & Push') {
            steps {
                dir('api-gateway') {
                    script {
                        docker.withRegistry('', DOCKER_CREDENTIALS_ID) {
                            def app = docker.build("${DOCKER_IMAGE}:latest")
                            app.push()
                        }
                    }
                }
            }
        }
    }
}
