pipeline {
    agent any

    environment {
        DOCKER_IMAGE = 'abkaur95/frontend'
        DOCKER_CREDENTIALS_ID = 'dockerhub'
    }

    stages {
        stage('Build') {
            steps {
                dir('frontend') {
                    sh 'npm install'
                    // Override CI env to avoid breaking build on ESLint warnings
                    sh 'CI=false npm run build'
                }
            }
        }

        stage('Docker Build & Push') {
            steps {
                dir('frontend') {
                    script {
                        docker.withRegistry('', DOCKER_CREDENTIALS_ID) {
                            def app = docker.build("${DOCKER_IMAGE}:latest")
                            app.push()
                        }
                    }
                }
            }
        }
    }
}

