pipeline {
    agent any

    environment {
        DOCKER_IMAGE = 'your-dockerhub-username/cinevision-movie-service'
        DOCKER_CREDENTIALS_ID = 'dockerhub'
    }

    stages {
        stage('Checkout') {
            steps {
                git credentialsId: 'git-hub', url: 'https://github.com/your-github-username/CineVisionMicroserviceProject.git'
            }
        }

        stage('Build') {
            steps {
                dir('movieService') {
                    sh 'mvn clean install -DskipTests'
                }
            }
        }

        stage('Docker Build & Push') {
            steps {
                dir('movieService') {
                    script {
                        docker.withRegistry('', DOCKER_CREDENTIALS_ID) {
                            def app = docker.build("${DOCKER_IMAGE}:latest")
                            app.push()
                        }
                    }
                }
            }
        }
    }
}

